id: P005617
initial_creation_type: ocr
created_at: 31/03/2020
last_modified_at: 2021-12-17 12:07:25.434900
source_metadata:
  id: bdr:W20444
  title: བདུད་འཇོམས་ཚང་གི་རང་རྣམ
  author: ''
  volumes:
    58cfec9eb7fa4e029d2211d4c022f4f6:
      image_group_id: I4241
      title: ''
      volume_number: 1
      total_pages: 354
      base_file: v001.txt
  access: http://purl.bdrc.io/admindata/AccessOpen
  restrictedInChina: false
