id: I4412D202
source: https://library.bdrc.io
source_file: null
initial_creation_type: ocr
imported: '2020-03-31T23:02:53+00:00'
last_modified: '2022-06-08T05:20:00.629204+00:00'
parser: https://github.com/OpenPecha-dev/openpecha-toolkit/blob/231bba39dd1ba393320de82d4d08a604aabe80fc/openpecha/formatters/google_orc.py
source_metadata:
  id: bdr:W20444
  title: བདུད་འཇོམས་ཚང་གི་རང་རྣམ
  author: ''
  access: http://purl.bdrc.io/admindata/AccessOpen
  restrictedInChina: false
  base:
    DC29:
      image_group_id: I4241
      title: ''
      total_pages: 354
      order: 1
      base_file: DC29.txt
statistics: {}
quality: {}
copyright:
  status: Unknown
  notice: ''
  info_url: null
license: null
